### PR TITLE
Init: Defcoin support - add genesis block

### PR DESCRIPTION
**Pull request by V3ntus**
#25

### CODE REVIEW

**Comment by Lvl4Sword** [comment]
As detailed in 1.0 -- https://github.com/CryptocurrencyExplorer/CryptocurrencyExplorer/projects
this isn't going to be accepted until 1.0 is complete. Then we can work towards adding other coins.
There are other more important things to work on at the moment to get 1.0 ready.
One of those being taking the database schema from Abe, since the current schema is trash.

**Comment by V3ntus** [comment]
Ah ok thank you, good to know. In that case, I'll wait and possibly find other opportunities to contribute elsewhere here

**Comment by V3ntus** [comment]
@Lvl4Sword Another thing, Defcoin is a non-value coin, created for the infosec community to test and play around with. Would it still be considered early on as a viable alternative for testing purposes in this early development phase? Or is its early presence of utility not that significant?

**Comment by Lvl4Sword** [comment]
I've never heard of it before, but the PR can be accepted since it's very easy to add additional coins. Just personally trying to stick to the 1.0 plan is all.

**Review by Lvl4Sword — COMMENTED** [review]
LGTM

**Comment by V3ntus** [comment]
> Just personally trying to stick to the 1.0 plan is all.  

Definitely understandable. Thanks!

**Pull request merged**
